version: "3"

services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - 3100:3100
    volumes:
      - ./loki:/etc/loki
    command: -config.file=/etc/loki/loki-config.yaml

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    ports:
      - 9080:9080
    volumes:
      # - /var/log:/var/log
      - ./promtail/log:/var/log
      - ./promtail:/etc/promtail
    command: -config.file=/etc/promtail/promtail-config.yaml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana/tmp:/etc/grafana/provisioning/datasources
      - ./grafana:/var/lib/grafana
    user: "0"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alertrules.yml:/etc/alertmanager/alertrules.yml

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - 9100:9100

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    ports:
      - 9093:9093
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/etc/alertmanager/data'

  alertmanager-bot:
    command:
      - --alertmanager.url=http://host.docker.internal:9093
      - --log.level=info
      - --store=bolt
      - --bolt.path=/data/bot.db
      - --telegram.admin=<my_id>
      - --telegram.token=<my_token>
    image: metalmatze/alertmanager-bot:latest
    user: root
    ports:
      - 8080:8080
    container_name: alertmanager-bot
    hostname: alertmanager-bot
    volumes:
      - ./data:/data

  web:
    build: .
    container_name: web
    ports:
      - 8000:5000
    volumes:
      - .:/code
    environment:
      FLASK_DEBUG: "True"

  redis:
    image: redis:latest
    container_name: redis



