global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

rule_files:
  - "/etc/alertmanager/alertrules.yml"

alerting:
  alertmanagers:
    - static_configs:
      - targets: ["host.docker.internal:9093"]


scrape_configs:
  - job_name: "node_exporter_3"
    static_configs:
      - targets: ["host.docker.internal:9100"]


  - job_name: "prometheus_3"
    static_configs:
      - targets: ["host.docker.internal:9090"]


  - job_name: "my_web"
    static_configs:
      - targets: ["host.docker.internal:8000"]






    